app/src/Controller/RequestTrait.php
<?php

declare(strict_types=1);

namespace App\Controller;

use Symfony\Component\HttpFoundation\Request;

trait RequestTrait
{
    protected function getRequest(): Request
    {
        return $this->requestStack->getCurrentRequest();
    }
}

app/templates/partial/filters.html.twig
<div class="col-12 my-1">
    <div class="fw-light" > 
        <small>Pages: {{ pagination.getPageCount() }}</small>
        <small>Items: {{ pagination.getTotalItemCount() }}</small>
    </div>
</div>
<div class="col-md-6">
<form action="{{ path(pathName) }}" method="get" class="d-flex">
    <input type="hidden" name="page" value="{{ app.request.query.get('page', 1) }}" />
    <input type="hidden" name="filterField" value="{{ app.request.query.get('filterField', '') }}" />
    <input type="hidden" name="filterValue" value="{{ app.request.query.get('filterValue', '') }}" />
    <input type="hidden" name="page" value="{{ app.request.query.get('page', 1) }}" />
    <div class="input-group">
        <span class="input-group-text" id="itemsOnPage">Items on page</span>
        <select style="max-width: 6em;"class="form-select" name="limit" aria-label="Items on page" aria-describedby="itemsOnPage">
            <option value="6" {{ app.request.query.get('limit') == '6' ? 'selected' : '' }}>6</option>
            <option value="12" {{ app.request.query.get('limit') == '12' ? 'selected' : '' }}>12</option>
            <option value="24" {{ app.request.query.get('limit') == '24' ? 'selected' : '' }}>24</option>
            <option value="48" {{ app.request.query.get('limit') == '48' ? 'selected' : '' }}>48</option>
        </select>
        <button class="btn btn-primary" type="submit" id="button-addon2">Apply</button>
    </div>
</form>
</div>
<div class="col-md-6">
    {{ knp_pagination_filter( pagination, { (field): fieldName }) }}
</div>

app/templates/partial/flashes.html.twig
{% for label, messages in app.flashes %}
    {% for message in messages %}
        <div class="alert alert-{{ label }} alert-dismissible fade show shadow" role="alert">
            <strong>Holy guacamole!</strong>
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endfor %}

app/templates/partial/footer.html.twig
<hr>
<span>Bingo Bongo &copy; {{ 'now'|date('Y') }} Recipe App</span>

app/templates/partial/listHeader.html.twig
<div class="row">
    <h1 class="mt-4 mb-4"><i class="{{ icon ?? "" }}"></i> {{ header }}:</h1>
</div>
{% block filters %}
    <div class="row">
    {% 
        include 'partial/filters.html.twig' 
        with { 'pagination': pagination, 'field': field, 'fieldName': fieldName, 'pathName': pathName } 
    %}
    </div>
{% endblock %}

app/templates/partial/menu.html.twig
<ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li class="nav-item">
        <a class="nav-link" href="{{ path('recipe_list') }}">
            Recipe list <i class="fa-solid fa-lemon mx-1"></i>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="favouriteLink" href="{{path('recipe_favs')}}">
        Favourite recipes <i class="fa-solid fa-heart mx-1"></i></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ path('category_list') }}">
        Categories <i class="fa-solid fa-pepper-hot mx-1"></i></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ path('ingredient_list') }}">
            Ingredients <i class="fa-solid fa-carrot mx-1"></i>
        </a>
    </li>
</ul>

<ul class="navbar-nav ms-auto">
    <li class="nav-item">
        <a class="nav-link" href="{{ path('app_logout') }}">
            Logout <i class="fa-solid fa-right-from-bracket mx-1"></i>
        </a>
    </li>
</ul>

app/templates/partial/pagination.html.twig
<div class="row my-5">
    <div class="navigation d-flex justify-content-center">
        {{ knp_pagination_render(pagination) }}
    </div>
</div>